name: frontend_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  flutter_localizations:
    sdk: flutter

  # ✅ Google Fonts (للخط الحلو)
  google_fonts: ^6.1.0

  # ✅ تخزين محلي
  shared_preferences: ^2.3.3

  # ✅ رفع الصور
  image_picker: ^1.1.2

  # ✅ الرسومات (للأدمن)
  fl_chart: ^0.66.2

  # ✅ API
  http: ^1.1.0

  # ✅ أيقونات إضافية
  phosphor_flutter: ^2.0.0

  # ✅ تواصل (واتساب / اتصال)
  url_launcher: ^6.2.5

  # ✅ Inbox swipe
  flutter_slidable: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  windows:
    generate: true
    image_path: "assets/logo1.png"
  web:
    generate: true
    image_path: "assets/logo1.png"
  image_path: "assets/logo1.png"

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/logo1.png
